### ISSUE TITLE
Exclude Map example is not working as is

### ISSUE THREAD

**Issue by tizzle** [kimchristiansen/poisson-disk-sampler-js#1]
Hey Kim,

great work  and thanks for sharing it!

i just tested your code and found out that your excludeMap example isn't running as it should.
The black pixels (and it is #000000, i checked twice) in your excludeMap.jpg return a value of 1 (instead of 0), when getExcludeMapPixel is called on those coordinates. In combination with the initial excludeThreshold of 0 this leads to the excludeMap not being applied at all. 
A quick fix is to raise the threshold to 1.

Have a nice weekend!

Best regards

Till

**Comment by kimchristiansen** [comment]
Hey Till,

thanks finding the issue. I changed the threshold from 0 to 1.
I must confess that i am not active developing the poisson-disk-sampler.

Best regards
Kim
